[package]
name = "bad-bets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = {version = "0.4.33", features = ["serde"] }
serde = "1.0.196"
serde_json = "1.0.113"
yahoo_finance_api = "2.1.0"
